### ISSUE TITLE
Issue subscribing to market changes

### ISSUE THREAD

**Issue by yosh7** [CCob/bittrex4j#39]
kudos for the package ! 
Please help.. I'm aiming to get live market data via the websocket (no trading actions at all).
I'm trying to work through the 'ShowRealTimeFills' sample. I implemented a simple println on all 6  event callbacks -onUpdateSummaryState, onUpdateExchangeState, onOrderStateChange, onBalanceStateChange, onWebsocketError, onWebsocketStateChange.

next i subscribe to market changes using (inside the connectWebsocket runnable,ofcourse):
```
                bittrexExchange.subscribeToExchangeDeltas("BTC-ETH", res -> {System.out.println("subscribed deltas1 "+res);});
                bittrexExchange.subscribeToMarketSummaries(res-> {System.out.println("subscribed summaries"+res);	});

```

I can see the socket connecting fine (using the onWebsocket events). I can also trigger standard REST methods, but I am not getting any calls to the event handlers - eg for the onUpdateSummaryState, where I can update the last bid/ask in my business logic.

Any idea what I am doing wrong?

**Comment by CCob** [comment]
It's hard to tell from the code you have provided.  Can you include a more complete example of what you are doing?

**Comment by yosh7** [comment]
gladly - here is the complete source + output follows:

```
    public static void main(String[] args) throws IOException {

        try(BittrexExchange bittrexExchange = new BittrexExchange(KEY,SECRET)) {
            bittrexExchange.onUpdateSummaryState(exchangeSummaryState -> {
            	System.out.println("onUpdateSummaryState");
                if (exchangeSummaryState.getDeltas().length > 0) {
                    Arrays.stream(exchangeSummaryState.getDeltas())
                            .forEach(marketSummary -> System.out.println(
                                    String.format("24 hour volume for market %s: %s",
                                            marketSummary.getMarketName(),
                                            marketSummary.getVolume().toString())));
                }
            });
            
            bittrexExchange.onUpdateExchangeState(updateExchangeState -> {
            	System.out.println("onUpdateExchangeState");
                double volume = Arrays.stream(updateExchangeState.getFills())
                        .mapToDouble(Fill::getQuantity)
                        .sum();

                if(updateExchangeState.getFills().length > 0) {
                    System.out.println(String.format("N: %d, %02f volume across %d fill(s) for %s", updateExchangeState.getNounce(),
                            volume, updateExchangeState.getFills().length, updateExchangeState.getMarketName()));
                }
            });

            bittrexExchange.onOrderStateChange(orderDelta -> {
            	System.out.println("onOrderStateChange");
                if(orderDelta.getType() == OrderType.Open || orderDelta.getType() == OrderType.Partial){
                    System.out.println(String.format("%s order open with id %s, remaining %.04f", orderDelta.getOrder().getExchange(),
                            orderDelta.getOrder().getOrderUuid(),orderDelta.getOrder().getQuantityRemaining()));
                }else if(orderDelta.getType() == OrderType.Filled ){
                    System.out.println(String.format("%s order with id %s filled, qty %.04f", orderDelta.getOrder().getExchange(),
                            orderDelta.getOrder().getOrderUuid(),orderDelta.getOrder().getQuantity()));
                }else if(orderDelta.getType() == OrderType.Cancelled){
                    System.out.println(String.format("%s order with id %s cancelled", orderDelta.getOrder().getExchange(),
                            orderDelta.getOrder().getOrderUuid()));
                }
            });

            bittrexExchange.onBalanceStateChange(balanceDelta -> {
                System.out.println(String.format("%s wallet balance updated, available: %s, pending: %s", balanceDelta.getBalance().getCurrency(),
                        balanceDelta.getBalance().getAvailable(),balanceDelta.getBalance().getPending()));
            });

        	bittrexExchange.onWebsocketError(e -> { System.out.println("webscok err");e.printStackTrace(); });
        	bittrexExchange.onWebsocketStateChange(stateChange -> {System.out.println(String.format("websock %s -> %s",stateChange.getOldState(),stateChange.getNewState()));});
            bittrexExchange.connectToWebSocket(() -> {
                bittrexExchange.subscribeToExchangeDeltas("BTC-ETH", res -> {System.out.println("subscribed deltas1 "+res);});
                bittrexExchange.subscribeToMarketSummaries(res-> {System.out.println("subscribed summaries"+res);	});
            });


            System.out.println("Press any key to quit");
            System.in.read();
            System.exit(-1);
        } catch (Exception e) {
        	System.out.println("EXCEPtion");
        	e.printStackTrace();
        }
        System.out.println("Closing websocket and exiting");
    }
}
```

output is:
```
websock Disconnected -> Connecting
Press any key to quit
websock Connecting -> Connected
subscribed summariestrue
subscribed deltas1 true
```
after that application is still running (waiting for sys input) but no additional sys out logging.

**Comment by CCob** [comment]
Hmm.  Can't see anything untoward.  Does the sample ShowRealtimeFills work?

**Comment by yosh7** [comment]
I checked the logs and found there are numerous parsing errors for the results. I shortened the logic to just one subscription:
```
bittrexExchange.connectToWebSocket(() -> {
	bittrexExchange.subscribeToExchangeDeltas("BTC-ETH", res -> {System.out.println("subscribed deltas1 "+res);});
});
```

here is the log subscription sent parsing errors of incoming msgs:
```
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Sending: {"I":"2","H":"c2","M":"subscribeToExchangeDeltas","A":["BTC-ETH"]}
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubProxy c2 - Executing invocation callback for: subscribeToExchangeDeltas
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubProxy c2 - Found result invoking method on hub: true
subscribed deltas1 true
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] ERROR com.github.ccob.bittrex4j.BittrexExchange - Failed to parse response
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "M" (class com.github.ccob.bittrex4j.dao.UpdateExchangeState), not marked as ignorable (10 known properties: "fills", "Sells", "f", "MarketName", "Nounce", "Buys", "sells", "marketName", "nounce", "buys"])
 at [Source: org.apache.http.client.entity.DeflateInputStream@6f99790b; line: 1, column: 187] (through reference chain: com.github.ccob.bittrex4j.dao.UpdateExchangeState["M"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1485)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1439)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:487)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1626)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1186)
	at com.github.ccob.bittrex4j.BittrexExchange.lambda$registerForEvent$1(BittrexExchange.java:196)
	at com.github.signalr4j.client.hubs.HubProxy$13.run(HubProxy.java:499)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.github.signalr4j.client.hubs.HubProxy$8.run(HubProxy.java:446)
	at com.github.signalr4j.client.hubs.HubProxy$8.run(HubProxy.java:423)
	at com.github.signalr4j.client.hubs.Subscription.onReceived(Subscription.java:31)
	at com.github.signalr4j.client.hubs.HubProxy.invokeEvent(HubProxy.java:413)
	at com.github.signalr4j.client.hubs.HubConnection.onReceived(HubConnection.java:118)
	at com.github.signalr4j.client.transport.TransportHelper.processReceivedData(TransportHelper.java:96)
	at com.github.signalr4j.client.Connection.processReceivedData(Connection.java:755)
	at com.github.signalr4j.client.Connection.access$000(Connection.java:29)
	at com.github.signalr4j.client.Connection$10.onData(Connection.java:693)
	at com.github.signalr4j.client.transport.WebsocketTransport$1.onMessage(WebsocketTransport.java:127)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:360)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:696)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:287)
	at java.lang.Thread.run(Unknown Source)
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] ERROR com.github.ccob.bittrex4j.BittrexExchange - Failed to parse response
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "M" (class com.github.ccob.bittrex4j.dao.UpdateExchangeState), not marked as ignorable (10 known properties: "fills", "Sells", "f", "MarketName", "Nounce", "Buys", "sells", "marketName", "nounce", "buys"])
 at [Source: org.apache.http.client.entity.DeflateInputStream@26b95789; line: 1, column: 187] (through reference chain: com.github.ccob.bittrex4j.dao.UpdateExchangeState["M"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1485)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1439)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:487)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1626)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1186)
	at com.github.ccob.bittrex4j.BittrexExchange.lambda$registerForEvent$1(BittrexExchange.java:196)
	at com.github.signalr4j.client.hubs.HubProxy$13.run(HubProxy.java:499)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.github.signalr4j.client.hubs.HubProxy$8.run(HubProxy.java:446)
	at com.github.signalr4j.client.hubs.HubProxy$8.run(HubProxy.java:423)
	at com.github.signalr4j.client.hubs.Subscription.onReceived(Subscription.java:31)
	at com.github.signalr4j.client.hubs.HubProxy.invokeEvent(HubProxy.java:413)
	at com.github.signalr4j.client.hubs.HubConnection.onReceived(HubConnection.java:118)
	at com.github.signalr4j.client.transport.TransportHelper.processReceivedData(TransportHelper.java:96)
	at com.github.signalr4j.client.Connection.processReceivedData(Connection.java:755)
	at com.github.signalr4j.client.Connection.access$000(Connection.java:29)
	at com.github.signalr4j.client.Connection$10.onData(Connection.java:693)
	at com.github.signalr4j.client.transport.WebsocketTransport$1.onMessage(WebsocketTransport.java:127)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:360)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:696)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:287)
	at java.lang.Thread.run(Unknown Source)
[Thread-4] INFO com.github.ccob.bittrex4j.BittrexExchange.WebSockets - HubConnection - Processing message
[Thread-4] ERROR com.github.ccob.bittrex4j.BittrexExchange - Failed to parse response
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "M" (class com.github.ccob.bittrex4j.dao.UpdateExchangeState), not marked as ignorable (10 known properties: "fills", "Sells", "f", "MarketName", "Nounce", "Buys", "sells", "marketName", "nounce", "buys"])
 at [Source: org.apache.http.client.entity.DeflateInputStream@2555eae2; line: 1, column: 187] (through reference chain: com.github.ccob.bittrex4j.dao.UpdateExchangeState["M"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1485)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1439)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:487)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1198)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:314)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:148)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1626)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1186)
	at com.github.ccob.bittrex4j.BittrexExchange.lambda$registerForEvent$1(BittrexExchange.java:196)
	at com.github.signalr4j.client.hubs.HubProxy$13.run(HubProxy.java:499)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.github.signalr4j.client.hubs.HubProxy$8.run(HubProxy.java:446)
	at com.github.signalr4j.client.hubs.HubProxy$8.run(HubProxy.java:423)
	at com.github.signalr4j.client.hubs.Subscription.onReceived(Subscription.java:31)
	at com.github.signalr4j.client.hubs.HubProxy.invokeEvent(HubProxy.java:413)
	at com.github.signalr4j.client.hubs.HubConnection.onReceived(HubConnection.java:118)
	at com.github.signalr4j.client.transport.TransportHelper.processReceivedData(TransportHelper.java:96)
	at com.github.signalr4j.client.Connection.processReceivedData(Connection.java:755)
	at com.github.signalr4j.client.Connection.access$000(Connection.java:29)
	at com.github.signalr4j.client.Connection$10.onData(Connection.java:693)
	at com.github.signalr4j.client.transport.WebsocketTransport$1.onMessage(WebsocketTransport.java:127)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:360)
	at org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:696)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:367)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:212)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:287)
	at java.lang.Thread.run(Unknown Source)

```

**Comment by CCob** [comment]
You are running the latest version right?

**Comment by yosh7** [comment]
1.0.10

**Comment by CCob** [comment]
Can you try 1.0.11-SNAPSHOT to see if that works.  You'll need to enable the sonatype maven repo for this.

**Comment by asemikov** [comment]
> [Thread-4] ERROR com.github.ccob.bittrex4j.BittrexExchange - Failed to parse response
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "M" (class com.github.ccob.bittrex4j.dao.UpdateExchangeState), not marked as ignorable (10 known properties: "fills", "Sells", "f", "MarketName", "Nounce", "Buys", "sells", "marketName", "nounce", "buys"])
 at [Source: org.apache.http.client.entity.DeflateInputStream@6f99790b; line: 1, column: 187] (through reference chain: com.github.ccob.bittrex4j.dao.UpdateExchangeState["M"])

Hi,
@yosh7 seems to be you're missing dependency for JsonAlias annotation.
I've fixed this error by adding following dependencies:
```
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.9.4</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.9.4</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.4</version>
        </dependency>
```

**Comment by yosh7** [comment]
Problem solved...

I first added the 3 dependencies to my project (I used builds 2.9.6), but still got the same error.
I than created a clean project and started the minimal example from scratch and everything worked. so I started reviewing my list of dependencies, until i found a jar that contained all it dependencies including the older versions of jackson, once there it was easy to resolve the clashing references.

many thanks for your time and efforts here !
