### ISSUE TITLE
Lots of exceptions thrown

### ISSUE THREAD

**Issue by cymp** [CCob/bittrex4j#52]
Hello,

I am subscribing to all of the markets and getting periodically lots of:
```
java.lang.Exception: There was an error invoking Hub method 'c2.queryExchangeState'.
	at com.github.signalr4j.client.hubs.HubProxy$2.run(HubProxy.java:229)
	at com.github.signalr4j.client.hubs.HubProxy$2.run(HubProxy.java:219)
	at com.github.signalr4j.client.hubs.HubConnection.onReceived(HubConnection.java:92)
	at com.github.signalr4j.client.transport.TransportHelper.processReceivedData(TransportHelper.java:53)
	at com.github.signalr4j.client.Connection.processReceivedData(Connection.java:755)
	at com.github.signalr4j.client.Connection.access$000(Connection.java:29)
	at com.github.signalr4j.client.Connection$10.onData(Connection.java:693)
	at com.github.signalr4j.client.transport.WebsocketTransport$1.onMessage(WebsocketTransport.java:127)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:292)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:417)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:170)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:229)
	at java.lang.Thread.run(Thread.java:748)
```

I can't find the reason why I'm getting those, is this something I should care about?

**Comment by cymp** [comment]
Any idea?

**Comment by CCob** [comment]
Is that the lowest exception in the chain?

**Comment by cymp** [comment]
Yes

**Comment by CCob** [comment]
I would put a BP here - https://github.com/signalr4j/signalr4j/blob/588245ac52598bc8d3f054b60e7e889ab41b7e2d/src/main/java/com/github/signalr4j/client/hubs/HubProxy.java#L229

Looks like the method call on websocket is failing.  Maybe there is more information in the HubResult class that the exception is not showing

**Comment by cymp** [comment]
Ok, will try thanks.
